### ISSUE TITLE
'Load_in_8bit' Error

### ISSUE THREAD

**Issue by ghost** [Bavest/fin-llama#1]
```bash

Downloading (…)lve/main/config.json: 100%|███████████████████████████| 576/576 [00:00<00:00, 835kB/s]
Traceback (most recent call last):
  File "/Users/evan/ai/LLMs/fin-llama/example/example.py", line 5, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2312, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes`
```

This error is generated most times in my local code; I decided to try the example.py file to see if it may be my file but I'm still having no luck finding the solution.

I'm still pretty new to LLMs and Datasets so any info or help is definitely appreciated!

**Comment by monolidth** [comment]
Hi, you need to install the right dependencies.

1. Remove prev. dependencies
`pip uninstall -r requirements.txt`

2. Reinstall
`pip install -r requirements.txt`

I hope, this will help you.

Regards,
William

**Comment by ghost** [comment]
Np. I'll update tomorrow. I'm reading into the project docs and comments, so I'll try and troubleshoot it. 
I see you're involved with the project, so I'll follow and keep you updated... !



Thanks, 
Evan

**Comment by monolidth** [comment]
Its in the README as well:
> To load models in 4bits with transformers and bitsandbytes, you have to install accelerate and transformers from source and make sure you have the latest version of the bitsandbytes library (0.39.0).


The issue is, that you likely have other dependency versions installed.

**Comment by kid-gorgeous** [comment]
Danke! I will install them from the source and try again.
